data:
  metadata_path: "../data/processed_datasets/metadata/all_voice_metadata.json"
  data_dir: "../data"
  sample_rate: 22050
  
model:
  unfreeze_last_n_layers: 0  # Start with frozen XTTS, only train adapter
  
training:
  num_epochs: 3
  learning_rate: 5e-5
  batch_size: 1  # XTTS works best with batch_size=1
  
  # Loss weights
  valence_weight: 1.0
  arousal_weight: 1.0
  consistency_weight: 0.1
  regularization_weight: 0.01
  
  # Checkpointing
  checkpoint_every: 3000
  
optimization:
  weight_decay: 0.01
  gradient_clip_norm: 1.0
  
paths:
  checkpoint_dir: "checkpoints/valence_arousal_xtts"
  log_dir: "logs/valence_arousal_xtts"

# XTTS model location
xtts:
  local_model_dir: "./models/xtts_v2"

# Hardware settings
device: "cuda"
num_workers: 4

# Reproducibility
seed: 42